# RepoInsight Plugin Configuration

# GithubBot API Configuration
github_bot_api:
  base_url: "http://localhost:8000"
  timeout: 30
  retry_attempts: 3
  retry_delay: 5

# User Session Configuration
user_session:
  max_sessions_per_user: 5
  session_timeout_hours: 24
  max_question_length: 1000
  cleanup_interval_hours: 24

# Default Embedding Configuration
default_embedding_config:
  provider: "openai"
  model: "text-embedding-ada-002"
  api_key: "your-openai-api-key"
  max_tokens: 8192
  chunk_size: 1000
  chunk_overlap: 200

# Default LLM Configuration
default_llm_config:
  provider: "openai"
  model: "gpt-4"
  api_key: "your-openai-api-key"
  max_tokens: 4096
  temperature: 0.7
  generation_mode: "balanced"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "repo_insight.log"
  max_file_size: "10MB"
  backup_count: 5

# Database Configuration
database:
  path: "repo_insight.db"
  connection_timeout: 30
  max_connections: 10

# Polling Configuration
polling:
  analysis_status_interval: 10
  query_result_interval: 5
  cleanup_interval: 3600

# Feature Flags
features:
  enable_group_chat: true
  enable_private_chat: true
  require_mention_in_group: true
  auto_cleanup: true
  enable_analytics: false

# Performance Configuration
performance:
  max_concurrent_requests: 10
  request_timeout: 60
  cache_ttl: 3600